name: Terragrunt Destroy

on: 
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- NEW STEP: Install Terraform ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7 # Use the same version you used for deploy

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: 0.55.0

      - name: Terragrunt Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          PROD_PATH=$(find . -name "prod" -type d | grep -v ".terragrunt-cache" | head -n 1)
          cd "$PROD_PATH" && terragrunt destroy --terragrunt-non-interactive -auto-approve
